---

- name: Install alsa-utils and pulseaudio tools
  community.general.pacman:
    name:
      - alsa-utils
      - bluez
      - bluez-utils
      - pulseaudio
      - pulseaudio-alsa
      - pavucontrol
    state: present

- name: create directory for pulse
  ansible.builtin.file:
    path: "/home/{{ user.name }}/.config/pulse"
    state: directory
    owner: "{{ user.name }}"

- name: Deploy HiFi pulse audio daemon configuration
  ansible.builtin.template:
    src: daemon.conf.j2
    dest: "/home/{{ user.name }}/.config/pulse/daemon.conf"
  become_user: "{{ user.name }}"
  become: true

- name: Start systemd service - bluetooth.service
  ansible.builtin.systemd:
    name: bluetooth.service
    state: started
    enabled: yes
  become: true
